# This the base backuper.conf file
# This file rely on the Toml syntax

[transporter.google]
client = "change me"
private_key = "change me"
email = "change me"
url = "change me"
folder_id = "change me"

[saver.db]
archive = false
host = "127.0.0.1"
port = 3306
user = "change me"
password = "change me"
database = "change me"
# Supported drivers are mysql or postgresql
driver = "mysql"

[saver.cache]
archive = false
host = "127.0.0.1"
port = 6379
# Supported drivers are redis
driver = "redis"

[saver.files]
archive = true
path = "/home/"
# array of files to backup
files = []
# If given will protect archive with password
archive_password = ""