name: Build Rust Backuper

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --bin rust_backuper
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: rs_backuper
          path: target/${{ matrix.BUILD_TARGET }}/rust_backuper

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Download release artifact
        uses: actions/download-artifact@v5
        with:
          name: rs_backuper
          path: ./rs_backuper
      - name: Release Rust Backuper
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: false

          files: ./rs_backuper
