name: Build Rust Backuper

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rust_backuper
            asset_name: rs_backuper-linux-x86_64

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            artifact_name: rust_backuper
            asset_name: rs_backuper-linux-x86_64-old

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rust_backuper
            asset_name: rs_backuper-macos-arm64

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rust_backuper
            asset_name: rs_backuper-macos-x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --bin rust_backuper --target ${{ matrix.target }}

      - name: Rename binary
        run: cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: false
          make_latest: true
          files: ./artifacts/*
